import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'alavykhan',
  description: 'Generated by create next app',
  icons:{
    icon:[
      '/favicon_io/favicon.ico?v=4',
    ],
    apple:[
      '/favicon_io/apple-touch-icon.png?v=4'
    ],
    shortcut:[
      '/favicon_io/apple-touch-icon.png'
    ]
  },
  manifest:'/site.webmanifest'
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
